select * from replay_message;
--drop table replay_message;
--CREATE TABLE IF NOT EXISTS replay_message (
--  paymentid text NOT NULL,
--  message text NOT NULL,
--  createdTime timestamp  NOT NULL,
--  expireTime timestamp  NOT NULL,
--  country varchar(2),
--  replay integer NOT NULL,
--  status text NOT NULL,
--  PRIMARY KEY (paymentid)
--);
--ALTER TABLE replay_message
--   ADD CONSTRAINT check_type
--   CHECK (status IN ('N', 'E','P','R') );